[package]
name = "finch-symbolic"
version = "0.1.1"
edition = "2024"
description = "Namesquatting for Rust port of Finch.jl"
license = "BSD-3-Clause"
repository = "https://github.com/hameerabbasi/finch-rs"

[dependencies]
dyn-eq = "0.1.3"
dyn-hash = "0.2.2"
seahash = "4.1.0"
